#BEDROOM LIGHT AUTOMATION
#If the user wants to they can use a drop down box to manually set the light scene and turn off flux automation or the sunrise alarm
- id: bedroom_light
  alias: Manual override control for bedroom lights
  trigger:
    platform: state
    entity_id: input_select.bedroom_manual_scene
  action:
    - service: switch.turn_off
      entity_id: switch.light_automation
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedroom_sunrise_active
    - service: scene.turn_on
      data_template:      
        entity_id: >
          {% if is_state("input_select.bedroom_manual_scene", "Daylight") %}
            scene.bedroom_on
          {%-elif is_state("input_select.bedroom_manual_scene", "Evening") %}
            scene.bedroom_evening
          {%-elif is_state("input_select.bedroom_manual_scene", "Night") %}
            scene.bedroom_night
          {%-elif is_state("input_select.bedroom_manual_scene", "Blue") %}
            scene.bedroom_blue
          {% else %}
            none
          {% endif %}
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_manual_scene
        option: Select a scene

#Every minute check if the time hits the alarm sliders and the alarm toggle is on anthe alarm isn't already active
#If true start the alarm
- id: sunrise_alarm
  alias: 'Sunrise alarm'
  trigger:
    platform: time
    minutes: '/1'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bedroom_sunrise_alarm
        state: 'on'
      - condition: state
        entity_id: input_boolean.bedroom_sunrise_active
        state: 'off'
      - condition: template
        value_template: '{{ now().strftime("%-H") | int  == states("input_number.alarmhours") | int and now().strftime("%-M") | int  == states("input_number.alarmminutes") | int }}'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.bedroom_sunrise_active
    - service: switch.turn_off
      entity_id: switch.light_automation
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_light_scene
        option: Sunrise
      #runs through 15 scenes that slowly increase in colour temperature
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_1
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_2
    - delay: 00:01    
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_3
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_4
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_5
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_6
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_7
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_8
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_9
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_10
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_11
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_12
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_13
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_14
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.sunrise_15
    - delay: 00:01
    - service: scene.turn_on
      data:      
        entity_id: scene.bedroom_on_auto
      #Allows normal automation to resume
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedroom_sunrise_active
    - service: switch.turn_on
      entity_id: switch.light_automation

#LIVING ROOM LIGHT SETTING
#If the user wants to they can use a drop down box to manually set the light scene and turn off automation or the sunrise alarm
- id: living_room_light
  alias: Manual override control for living room lights and lamp and the kitchen light.
  trigger:
    platform: state
    entity_id: input_select.living_room_manual_scene
  action:
    - service: switch.turn_off
      entity_id: switch.light_automation
    - service: scene.turn_on
      data_template:      
        entity_id: >
          {% if is_state("input_select.living_room_manual_scene", "Daylight") %}
            scene.living_room_on
          {%-elif is_state("input_select.living_room_manual_scene", "Evening") %}
            scene.living_room_evening
          {%-elif is_state("input_select.living_room_manual_scene", "Night") %}
            scene.living_room_night
          {%-elif is_state("input_select.living_room_manual_scene", "Blue") %}
            scene.living_room_blue
          {%-elif is_state("input_select.living_room_manual_scene", "Movie") %}
            scene.living_room_movie
          {% else %}
            none
          {% endif %}
    - service: input_select.select_option
      data:
        entity_id: input_select.living_room_manual_scene
        option: Select a scene
      
- id: flux
  alias: If Flux is on set the display variable to automatic
  trigger:
    platform: state
    entity_id: switch.light_automation
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_scene
        option: Automatic
    - service: input_select.select_option
      data:
        entity_id: input_select.living_room_scene
        option: Automatic      

# Multi-state presence detection     
- alias: Mark person as just arrived
  trigger:
    - platform: state
      entity_id: device_tracker.adrian_phone
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.iphone
      from: 'not_home'
      to: 'home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.adrian_phone' %}
            input_select.adrian_status_dropdown
          {% else %}
            input_select.sophie_status_dropdown
          {% endif %}
        option: >
          {% if trigger.entity_id == 'device_tracker.adrian_phone' %}
            {% if states.input_select.adrian_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% else %}
            {% if states.input_select.sophie_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% endif %}
 
- alias: Mark person as home
  trigger:
    - platform: state
      entity_id: input_select.adrian_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.sophie_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.adrian_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.sophie_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.adrian_status_dropdown' %}
            input_select.adrian_status_dropdown
          {% else %}
            input_select.sophie_status_dropdown
          {% endif %}
        option: Home
 
- alias: Mark person as just left
  trigger:
    - platform: state
      entity_id: device_tracker.adrian_phone
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.iphone
      from: 'home'
      to: 'not_home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.adrian_phone' %}
            input_select.adrian_status_dropdown
          {% else %}
            input_select.sophie_status_dropdown
          {% endif %}
        option: Just Left
 
- alias: Mark person as away
  trigger:
    - platform: state
      entity_id: input_select.adrian_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.sophie_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.adrian_status_dropdown' %}
            input_select.adrian_status_dropdown
          {% else %}
            input_select.sophie_status_dropdown
          {% endif %}
        option: Away
 
- alias: Mark person as extended away
  trigger:
    - platform: state
      entity_id: input_select.adrian_status_dropdown
      to: 'Away'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.sophie_status_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.adrian_status_dropdown' %}
            input_select.adrian_status_dropdown
          {% else %}
            input_select.sophie_status_dropdown
          {% endif %}
        option: Extended Away
