homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 20
  unit_system: metric
  time_zone: Europe/London

updater:

config:

discovery:

conversation:

history:

logbook:

sun:

tts:
  platform: google

frontend:

#Frontend layout
group: !include group.yaml

#Extra iFrame tab in the Frontend for router settings
panel_iframe:
  router:
    title: 'Router'
    icon: mdi:access-point-network
    url: 'http://192.168.0.1'

#Device tracking on the local network
device_tracker:
  - platform: sky_hub
    host: 192.168.0.1

#Support for Yeelight lights. Assign the lights a fixed IP address with the router first.
light:
  - platform: yeelight
    devices:
      192.168.0.50:
        name: Bedroom light 1
        transition: 2000
      192.168.0.51:
        name: Bedroom light 2
        transition: 2000
      192.168.0.52:
        name: Living room light 1
        transition: 2000
      192.168.0.53:
        name: Living room light 2
        transition: 2000
      192.168.0.54:
        name: Living room lamp 1
        transition: 2000

#F.lux light component
switch:
  platform: flux
  lights:
    - light.bedroom_light_1
    - light.bedroom_light_2
    - light.living_room_light_1
    - light.living_room_light_2
    - light.living_room_lamp_1
  name: Light Automation
  start_time: '7:30'
  stop_time: '23:30'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1700
  brightness: 220
  disable_brightness_adjust: False
  mode: mired

#Emulate a Phillips Hue bridge to allow Google Home to control Home Assistant
emulated_hue:
  type: google_home
  # Google Home does not work on different ports.
  listen_port: 80

scene: !include_dir_merge_list scenes/

automation: !include_dir_merge_list automation/

sensor:
#Weather from Darksky
  - platform: darksky
    api_key: !secret darksky_api
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - wind_speed
      - wind_bearing
      - cloud_cover
      - hourly_summary
      - daily_summary
#Time and date variables
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

# DHT22 sensor
  - platform: dht
    sensor: DHT22
    name: Living Room
    pin: 4
    monitored_conditions:
      - temperature
      - humidity
  
  - platform: template
    sensors:
      alarm_time:
        friendly_name: 'Alarm time'
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_slider.alarmhours") | int, states("input_slider.alarmminutes") | int) }}'
      weather_summary:
        friendly_name: 'Weather Summary'
        value_template: '{{ states("sensor.dark_sky_daily_summary") }} It will be {{ states("sensor.dark_sky_hourly_summary") }} It is currently {{ states("sensor.dark_sky_summary") }} and is {{ states("sensor.dark_sky_temperature") }}°C, but feels like {{ states("sensor.dark_sky_apparent_temperature") }}°C. There is a {{ states("sensor.dark_sky_precip_probability") }}% chance of rain.'
      bedroom_light_scene:
        friendly_name: 'Current Light Scene'
        value_template: '{{states("input_select.bedroom_scene") }}'
      living_room_light_scene:
        friendly_name: 'Current Light Scene'
        value_template: '{{states("input_select.living_room_scene") }}'
   
  - platform: moon


input_slider:

#Sunrise alarm clock variables
  alarmhours:
    name: Hour
    icon: mdi:timer
    initial: 7
    min: 0
    max: 23
    step: 1
  alarmminutes:
    name: Minutes
    icon: mdi:timer
    initial: 15
    min: 0
    max: 55
    step: 5

input_boolean:

#Bedroom light automation variables
  bedroom_light_automation:
    name: Automation toggle
    initial: on
    icon: mdi:brightness-auto
  bedroom_sunrise_alarm:
    name: Bedroom sunrise alarm
    initial: on
  bedroom_sunrise_active:
    name: Sunrise active
    initial: off
#Living room light variables
  living_room_light_automation:
    name: Automation toggle
    initial: on
    icon: mdi:brightness-auto

input_select:
    
#Bedroom light automation variables
  bedroom_manual_scene:
    name: Manual Light Scene
    options:
      - Daylight
      - Evening
      - Night
      - Blue
      - Select a scene
    initial: Select a scene
  bedroom_scene:
    name: Bedroom Light Scene
    options:
      - Daylight
      - Evening
      - Night
      - Blue
      - Sunrise
      - Automatic
    initial: Automatic

#Living room light automation variables
  living_room_manual_scene:
    name: Manual Light Scene
    options:
      - Daylight
      - Evening
      - Night
      - Movie
      - Blue
      - Select a scene
    initial: Select a scene
  living_room_scene:
    name: Living Room Light Scene
    options:
      - Daylight
      - Evening
      - Night
      - Movie
      - Blue
      - Automatic
    initial: Automatic
