- alias: If FLux is on set the display variable to automatic
  trigger:
    platform: state
    entity_id: switch.light_automation
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_scene
        option: Automatic
    - service: input_select.select_option
      data:
        entity_id: input_select.living_room_scene
        option: Automatic
